---
abstract: 'Interface to fetch country flag of an IP.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IP-CountryFlag
no_index:
  directory:
    - t
    - inc
requires:
  Data::Validate::IP: '0.10'
  File::Spec::Functions: '3.30'
  HTTP::Tiny: '0'
  Moo: '0'
  Throwable: '0'
  autodie: '2.06'
  namespace::clean: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Manwar/IP-CountryFlag.git
version: '0.06'
